### ISSUE TITLE
Falha ao criar personagem feminina

### ISSUE THREAD

**Issue by gitmonox** [Faroeste-Roleplay/frp-lua-rdr3#7]
![image](https://user-images.githubusercontent.com/52660130/127787864-c07a97fd-59e8-45f7-8505-7e575a946e0c.png)
Inclui personagem vindo sem roupas
![image](https://user-images.githubusercontent.com/52660130/127787867-aa6fabae-5c84-484a-94b5-d65bd55c5342.png)

**Comment by Nicoo34** [comment]
womans doesn't have chest by default in red dead, you just have to put clothes
